config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'product_list/index'

  resources :products
  get 'home/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/product_list_controller.rb
class ProductListController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:image, :name, :price, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_list_helper.rb
module ProductListHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to  "Sign Out" , destroy_user_session_path, method: :delete %>
    </li>
    Current User Email  : ----- 
    <%= current_user.email %>
    </li>
  <% else %>
     <li>
      <%= link_to  "Sign In" , new_user_session_path %>
    </li>
    <li>
      <%= link_to  "Sign Up" , new_user_registration_path %>
    </li>
  <% end %>

</ul>





<h1>SHOPPING KART</h1>


<%= link_to  "Product List" , product_list_index_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sk</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/product_list/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Availables Products</h1>






 <% @products.each do |product| %>
<div class="gallery">
  <a target="_blank" href="fjords.jpg">
    <%= image_tag product.image.url%>
  </a>
  <div class="desc">
   Name:  <%= product.name %><br/>
  Price:<%= product.price %><br/>
    <%= product.title %><br/>
   
  </div>
</div>
 <% end %>

app/views/products/_form.html.erb
<%= form_for @product, :html => { :multipart => true }  do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>
</div>
    <div class="field">
     <%= form.label :image %><br>
    <%= form.file_field :image, id: :reciepe_image %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Title:</strong>
  <%= image_tag @product.image.url %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<div class="outerDiv">
      <div class="leftDiv">
       <%= image_tag @product.image.url %>
      </div>
      <div class="rightDiv">
        This is Right DIV.
      </div>    
      <div "style: clear:both;"></div>
    </div>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>